### PR TITLE
Optional json schema deriver (+ quote crate update)

### PR DESCRIPTION
**Pull request by Voronar**

### CODE REVIEW

**Comment by SilentCicero** [comment]
@Voronar how goes the work on XDR?

We are looking into what Rust infra is available as we would like to use this schema heavily across our architecture. Is your PR up to spec?

**Comment by Voronar** [comment]
@SilentCicero It works as expected, according to https://crates.io/crates/schemars serialization/deserialization behavior just like if I manually marked XDR-generated structures with `JsonSchema` derive attribute.

_P.S._ I think this xdr-repo project is a little bit outdated (but works good) and I forked it for my purposes and it just works in my case. And I made this PR just for those who interested in this changes. May be @jsgf not interested in this changes. I don't know.

**Comment by SilentCicero** [comment]
@Voronar do you think you would be up for putting your updated version under a new project name?

We are looking at using XDR heavily in our blockchian, and ideally, we would like to work with a single updated solid package.

Do you know if your updated fork hits all the XDR spec tests?

What is your current uses for XDR ATM?

**Comment by Voronar** [comment]
@SilentCicero If we will not be able to ping @jsgf for project future details then starting new project is good idea.
My fork passes all old test cases and works for my new case ([pointer field case](https://github.com/jsgf/rust-xdr/issues/35)), but I did not add new test function yet.
I use simple xdr structures, enums, arrays, opaque types.
What is `XDR ATM`?

**Pull request closed without merging**
